### ISSUE TITLE
How to alter POD to use local version of js api

### ISSUE THREAD

**Issue by anthonyryan-ergon** [Esri/product-on-demand#12]
Hi there,
Would someone be able to let me know to modify the js of POD so it referenced a local copy of the api instead of using https://js.arcgis.com/3.13/...?
At present, we are experiencing intermittent 403 errors when trying to load different components of the api (eg. BasemapLayer.js, BasemapGallery.js, etc) from https://js.arcgis.com/3.13.

Thanks

**Comment by skmoore** [comment]
@aryan200o You can download a copy of the API here: https://developers.arcgis.com/downloads/

From there, you would have to deploy the API on your own web server, and change the URLs in the POD code to point to the location where you are hosting it.

**Comment by anthonyryan-ergon** [comment]
skmoore,

I was able to setup the local version and alter to the urls within POD to use this copy. Working so far.
