### ISSUE TITLE
http/https with server/webadaptor urls

### ISSUE THREAD

**Issue by anthonyryan-ergon** [Esri/product-on-demand#14]
Hi there,

I would like to confirm what format to the urls with podconfig.js, proxy.config, etc. are allowed?
We have a GP site (multiple Windows Server 2012 R2 VMs) with 'default' cluster which has the POD GP tools published, federated to portal & webadaptor installed, HTTPS only, etc.

When configuring the POD files, is https://webadaptor.domain/webadaptorname/rest/services (https://esri.myergon.local/gpsite/rest/services) allowed? The url works fined within the web browser.
I see the examples in the documentation as http://arcgisserver.domain.com:6080/arcgis/rest/services but can't see any notes stating this is the only way.

Thanks

**Comment by skmoore** [comment]
@aryan200o Yes, HTTPS urls should work fine. The only caveat is that you'll want to use the same protocol throughout (service URLs, API URLs, the URL to the app itself), otherwise you'll get mixed content warnings and/or failures.
